### ISSUE TITLE
The requested package koolreport/pro could not be found in any version, there may be a typo in the package name

### ISSUE THREAD

**Issue by OmdaMukhtar** [koolreport/dashboard-demo#1]
I am trying to use your Koolreport/pro package and after I register I got the autherization to login and get the composer info, it's seem like so as you mention on pup up composer
```
{
    "repositories":[
        {"type":"composer","url":"https://repo.koolreport.com"}
    ],
    "require":{
        "koolreport/pro":"*",
        "koolreport/blade":"*",
        "koolreport/export":"*"
    }
}
```

and the auth.json also look like so 
```
{
  "http-basic": {
    "repo.koolreport.com": {
      "username": "test@gmail.com",
      "password": "12345678"
    }
  }
}
```

and when I run `composer update` 
I get this
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package koolreport/pro could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package koolreport/blade ^4.5 exists as koolreport/blade[1.0.0, dev-master, dev-ver1.0.0] but these are rejected by your constraint.
  Problem 3
    - The requested package koolreport/export could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```
How could I make?

**Comment by koolreport** [comment]
Please try to generate new token key from your account and add to your auth.json. Furthermore

1. You don't need to put "koolreport/export" as the package is within "koolreport/pro" already
2. You need to add "koolreport/dashboard"=>"*" if you plan to run the dashboard-demo

**Comment by OmdaMukhtar** [comment]
I did as you said and I have got this 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package koolreport/dashboard could not be found in any version, there may be a typo in the package name
```

**Comment by koolreport** [comment]
Do you have license of KoolReport Pro and Dashboard Framework?

**Comment by OmdaMukhtar** [comment]
I don't have, but I need to use it first and then I will make a license.

**Comment by OmdaMukhtar** [comment]
@koolreport we are working to test it and then as I said we will buy, just we need to test our API on it.

**Comment by koolreport** [comment]
@OmdaMukhtar : Although we do not have the trial version that you can test on but we have 30-days money back guarantee. So you can go with purchase and then make a test. You have 30 days to decide whether you want to go with it. In case that KoolReport Pro and Dashboard Framework do not meet your requirements or even you find a better solution, you can tell us, we will refund fully to you.

FYI, we have 40% discount for KoolReport Pro and when you buy KoolReport Pro, you will get Dashboard Framework for free too. This is our biggest sale in year end.

We are looking forward to serving you.

**Comment by OmdaMukhtar** [comment]
Thank you for your help, I purchesed a lisiense
