### ISSUE TITLE
Data type issue : (real) cast is deprecated, use (float) instead 

### ISSUE THREAD

**Issue by haizad** [koolreport/dashboard-demo#3]
I got The (real) cast is deprecated, use (float) instead . koolreport\dashboard\Field.php. Works find after switch it into float.

**Comment by koolreport** [comment]
Yes, this issue happens when you are using dashboard version 1.0.0 with PHP >=7.4. We have solved the issue, you may upgrade to Dashboard latest 1.3.5, the issue was solved. Thank you very much!

**Comment by haizad** [comment]
Noted 🗡️
